/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.hostelmanagement.AfterLoginScreen.FeeDetails;

import com.mycompany.hostelmanagement.DBConnection.DBConnection;
import com.mycompany.hostelmanagement.SignUp.SignUpPage;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jahnavi
 */
public class FeeDetailsscreen extends javax.swing.JInternalFrame {

    /**
     * Creates new form FeeDetailsscreen
     */
     public Connection connection =null; 
    private static final Logger logger = Logger.getLogger(FeeDetailsscreen.class.getName());
    public String loginIdStatic;
   
    public FeeDetailsscreen(String loginId) {
        initComponents();
        connection = DBConnection.getConnection();
        loginIdStatic=loginId;
        refreshButton.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        totalAmount = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        amountPaid = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        amountDue = new javax.swing.JTextField();
        refreshButton = new javax.swing.JButton();
        notice = new javax.swing.JTextField();

        jTextField1.setEditable(false);
        jTextField1.setText("Total Amount");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setText("Amount Paid");

        amountPaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountPaidActionPerformed(evt);
            }
        });

        jTextField3.setEditable(false);
        jTextField3.setText("Amount Due");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        amountDue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountDueActionPerformed(evt);
            }
        });

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        notice.setEditable(false);
        notice.setForeground(new java.awt.Color(248, 12, 25));
        notice.setText("Note : Fee Details will be updated Within 24 Hours");
        notice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noticeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField3)
                            .addComponent(jTextField2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(totalAmount)
                            .addComponent(amountPaid)
                            .addComponent(amountDue, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(notice, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountPaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountDue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(refreshButton)
                .addGap(40, 40, 40)
                .addComponent(notice, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void amountPaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountPaidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountPaidActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void amountDueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountDueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountDueActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
         try {
             PreparedStatement readFromRegisterTable=connection.prepareStatement("select * from register where (profileId1=? or profileId2=?)");
             readFromRegisterTable.setString(1,loginIdStatic);
             readFromRegisterTable.setString(2,loginIdStatic);
             ResultSet isRegisteredSet = readFromRegisterTable.executeQuery();
             
             
            if(isRegisteredSet.next()){
                    logger.log(Level.INFO, "Entry found in register table for profile Id: {0}",loginIdStatic);
                    PreparedStatement readFromFeeDetailsTable=connection.prepareStatement("select * from feedetails where profileId=?");
                    readFromFeeDetailsTable.setString(1,loginIdStatic);
                    ResultSet profileIdResultSet = readFromFeeDetailsTable.executeQuery();
                    
                    if(profileIdResultSet.next()){
                       logger.log(Level.INFO, "Entry found in feedetails table for profile Id: {0}",loginIdStatic);
                       
                       String dbTotalAmount = profileIdResultSet.getString(3);
                       String dbAmountPaid = profileIdResultSet.getString(4);
                       String dbAmountDue = profileIdResultSet.getString(5);
                       
                       totalAmount.setText(dbTotalAmount);
                       amountPaid.setText(dbAmountPaid);
                       amountDue.setText(dbAmountDue);
                       
                       notice.setEditable(true);
                       notice.setText("Note : Fee Details will be updated Within 24 Hours");
                       notice.setEditable(false);
                    }else{
                        logger.log(Level.INFO, "Entry not found in feedetails table for profile Id: {0}",loginIdStatic);
                        notice.setEditable(true);
                        notice.setText("Unable to fetch Amount Details or not found");
                        notice.setEditable(false);
                    }
            }else{
                notice.setEditable(true);
                notice.setText("Please register first to pay fee");
                notice.setEditable(false);
                logger.log(Level.SEVERE, "Entry not found in register table for profile Id: {0}",loginIdStatic);
            }
             
         } catch (Exception ex) {
             Logger.getLogger(FeeDetailsscreen.class.getName()).log(Level.SEVERE, null, ex);
         }
        
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void noticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noticeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noticeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountDue;
    private javax.swing.JTextField amountPaid;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField notice;
    private javax.swing.JButton refreshButton;
    private javax.swing.JTextField totalAmount;
    // End of variables declaration//GEN-END:variables
}
