/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.hostelmanagement.AfterLoginScreen;

import com.mycompany.hostelmanagement.AfterLoginScreen.ProfileScreen.Profilescreen;
import com.mycompany.hostelmanagement.AfterLoginScreen.ChangePassword.ChangePasswordScreen;
import com.mycompany.hostelmanagement.AfterLoginScreen.FeeDetails.FeeDetailsscreen;
import com.mycompany.hostelmanagement.AfterLoginScreen.Registration.RegistrationScreen;
import com.mycompany.hostelmanagement.SignUp.SignUpPage;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;

/**
 *
 * @author pranay
 */
public class AfterLoginScreen extends javax.swing.JFrame {
    
    public static AfterLoginScreen afterLoginScreen=null;
    public static String loginIdStatic;
    private static final Logger logger = Logger.getLogger(AfterLoginScreen.class.getName());
    
    public Profilescreen profilescreen=null;
    public ChangePasswordScreen changePasswordScreen=null;
    public RegistrationScreen registrationScreen=null;
    public FeeDetailsscreen feeDetailsscreen=null;
    
    public int previousWindow=0;
    
    public void removeJpanelFrame(){
        if(previousWindow==1){
            getContentPane().remove(profilescreen);
        }else if(previousWindow==2){
            getContentPane().remove(registrationScreen);
        }else if(previousWindow==3){
            getContentPane().remove(feeDetailsscreen);
        }else if(previousWindow==4){
            
        }else if(previousWindow==5){
            
        }else if(previousWindow==6){
            getContentPane().remove(changePasswordScreen);
        }else{
            try {
                getContentPane().remove(mainFrame);
                mainFrame.setClosed(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(AfterLoginScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    public static AfterLoginScreen getAfterLoginScreen(String loginId){
       loginIdStatic = loginId;
       afterLoginScreen = new AfterLoginScreen();
       return afterLoginScreen;
    }

    /**
     * Creates new form AfterLoginScreen
     */
    public AfterLoginScreen() {
        initComponents();
        profileButton.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jFrame2 = new javax.swing.JFrame();
        logoutButton = new javax.swing.JButton();
        feeDetailsButton = new javax.swing.JButton();
        profileButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        mainFrame = new javax.swing.JInternalFrame();
        cpButton = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 180, 40));

        feeDetailsButton.setText("Fee Details");
        feeDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feeDetailsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(feeDetailsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 180, 40));

        profileButton.setText("Profile");
        profileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileButtonActionPerformed(evt);
            }
        });
        getContentPane().add(profileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 180, 40));

        registerButton.setText("Registration");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 180, 40));

        jButton7.setText("Room Swap");
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 180, 40));

        jButton8.setText("Notification");
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 180, 40));

        mainFrame.setVisible(true);

        javax.swing.GroupLayout mainFrameLayout = new javax.swing.GroupLayout(mainFrame.getContentPane());
        mainFrame.getContentPane().setLayout(mainFrameLayout);
        mainFrameLayout.setHorizontalGroup(
            mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mainFrameLayout.setVerticalGroup(
            mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(mainFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 550, 530));

        cpButton.setText("Change Password");
        cpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 180, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileButtonActionPerformed
        try {
        mainFrame.setClosed(true);
        removeJpanelFrame();
        previousWindow=1;
        logger.log(Level.INFO, "previous window number  : {0} ",previousWindow);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AfterLoginScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
   profilescreen = new Profilescreen(loginIdStatic);
   profilescreen.setVisible(true);
   getContentPane().add(profilescreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 550, 530));
   pack();
    }//GEN-LAST:event_profileButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        afterLoginScreen.setVisible(false);
        SignUpPage.getSignUpPage().setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void cpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpButtonActionPerformed
        try {
          removeJpanelFrame();
          previousWindow=6;
          logger.log(Level.INFO, "previous window number  : {0} ",previousWindow);
        } catch (Exception ex) {
            Logger.getLogger(AfterLoginScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        changePasswordScreen = new ChangePasswordScreen(loginIdStatic);
        changePasswordScreen.setVisible(true);
        getContentPane().add(changePasswordScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 550, 530));
        pack();
    }//GEN-LAST:event_cpButtonActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
          try {
            removeJpanelFrame();
            previousWindow=2;
            logger.log(Level.INFO, "previous window number  : {0} ",previousWindow);
        } catch (Exception ex) {
            Logger.getLogger(AfterLoginScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
         registrationScreen = new RegistrationScreen(loginIdStatic);
         registrationScreen.setVisible(true);
         getContentPane().add(registrationScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 550, 530));
         pack();
    }//GEN-LAST:event_registerButtonActionPerformed

    private void feeDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feeDetailsButtonActionPerformed
        // TODO add your handling code here:
         try {
            removeJpanelFrame();
            previousWindow=3;
            logger.log(Level.INFO, "previous window number  : {0} ",previousWindow);
        } catch (Exception ex) {
            Logger.getLogger(AfterLoginScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
         feeDetailsscreen = new FeeDetailsscreen(loginIdStatic);
         feeDetailsscreen.setVisible(true);
         getContentPane().add(feeDetailsscreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 550, 530));
         pack();
    }//GEN-LAST:event_feeDetailsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AfterLoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AfterLoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AfterLoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AfterLoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                afterLoginScreen =new AfterLoginScreen();
                afterLoginScreen.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cpButton;
    private javax.swing.JButton feeDetailsButton;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JButton logoutButton;
    private javax.swing.JInternalFrame mainFrame;
    private javax.swing.JButton profileButton;
    private javax.swing.JButton registerButton;
    // End of variables declaration//GEN-END:variables
}
