/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.hostelmanagement.AdminAfterLoginScreen.AddDishesScreen;

import com.mycompany.hostelmanagement.DBConnection.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pranay
 */
public class AddDishesScreen extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddDishesScreen
     */
    
    public Connection connection =null; 
    
    public AddDishesScreen() {
        initComponents();
        connection = DBConnection.getConnection();
        RefreshDishes.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resetDishes = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        dishField = new javax.swing.JTextField();
        addDishButton = new javax.swing.JButton();
        dishesStatus = new javax.swing.JTextField();
        RefreshDishes = new javax.swing.JButton();
        resetVotes = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resetDishes.setText("Reset Dishes");
        resetDishes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetDishesActionPerformed(evt);
            }
        });
        getContentPane().add(resetDishes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 180, 40));

        jTextField1.setEditable(false);
        jTextField1.setText("         Dish Name ");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 158, 41));
        getContentPane().add(dishField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 160, 40));

        addDishButton.setText("Add for Voting");
        addDishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDishButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addDishButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 150, 40));
        getContentPane().add(dishesStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 200, 368, 52));

        RefreshDishes.setText("Refresh");
        RefreshDishes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshDishesActionPerformed(evt);
            }
        });
        getContentPane().add(RefreshDishes, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 137, -1));

        resetVotes.setText("Reset Votes");
        resetVotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetVotesActionPerformed(evt);
            }
        });
        getContentPane().add(resetVotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 120, 150, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addDishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDishButtonActionPerformed
        try {
            // TODO add your handling code here:
            String dishName = dishField.getText();
            PreparedStatement insertIntoDishesTable=connection.prepareStatement("insert into dishesTable(dishName) values(?)");
            insertIntoDishesTable.setString(1,dishName);
            insertIntoDishesTable.executeUpdate();
            RefreshDishes.doClick();
        } catch (SQLException ex) {
            Logger.getLogger(AddDishesScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addDishButtonActionPerformed

    private void RefreshDishesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshDishesActionPerformed
        String dishes="Dishes Today: ";  
        try {
            PreparedStatement readFromDishesTable=connection.prepareStatement("select  * from  dishesTable");
            ResultSet resultSet = readFromDishesTable.executeQuery();
             while(resultSet.next()){
                dishes=dishes+resultSet.getString(2)+", ";
            }
             dishesStatus.setText(dishes);
        } catch (SQLException ex) {
            Logger.getLogger(AddDishesScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RefreshDishesActionPerformed

    private void resetDishesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetDishesActionPerformed
          try {
            PreparedStatement insertIntoDishesTable=connection.prepareStatement("truncate dishesTable");
            insertIntoDishesTable.executeUpdate();
            RefreshDishes.doClick();
        } catch (SQLException ex) {
            Logger.getLogger(AddDishesScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_resetDishesActionPerformed

    private void resetVotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetVotesActionPerformed
           try {
            PreparedStatement insertIntoDishesTable=connection.prepareStatement("truncate dishVoters");
            insertIntoDishesTable.executeUpdate();
            RefreshDishes.doClick();
        } catch (SQLException ex) {
            Logger.getLogger(AddDishesScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_resetVotesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RefreshDishes;
    private javax.swing.JButton addDishButton;
    private javax.swing.JTextField dishField;
    private javax.swing.JTextField dishesStatus;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton resetDishes;
    private javax.swing.JButton resetVotes;
    // End of variables declaration//GEN-END:variables
}
