/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.hostelmanagement.AdminAfterLoginScreen;

import com.mycompany.hostelmanagement.AdminAfterLoginScreen.AddDishesScreen.AddDishesScreen;
import com.mycompany.hostelmanagement.AdminAfterLoginScreen.SearchStudentScreen.SearchStudentScreen;
import com.mycompany.hostelmanagement.AfterLoginScreen.AfterLoginScreen;
import static com.mycompany.hostelmanagement.AfterLoginScreen.AfterLoginScreen.afterLoginScreen;
import static com.mycompany.hostelmanagement.AfterLoginScreen.AfterLoginScreen.loginIdStatic;
import com.mycompany.hostelmanagement.AfterLoginScreen.Notifications.NotificationScreen;
import com.mycompany.hostelmanagement.SignUp.SignUpPage;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author pranay
 */
public class AdminAfterLoginScreen extends javax.swing.JFrame {

    /**
     * Creates new form AdminAfterLoginScreen
     */
    public int previousWindow=0;
    public AddDishesScreen addDishesScreen=null;
    public SearchStudentScreen searchStudentScreen=null;
    
    private static final Logger logger = Logger.getLogger(AdminAfterLoginScreen.class.getName());
    public static String AdminId;
    public static AdminAfterLoginScreen adminAfterLoginScreen=null;
    
     public static AdminAfterLoginScreen getAfterLoginScreen(String adminId){
       AdminId = adminId;
       adminAfterLoginScreen = new AdminAfterLoginScreen();
       return adminAfterLoginScreen;
    }

    
     public void removeJpanelFrame(){
        if(previousWindow==1){
            getContentPane().remove(searchStudentScreen);
        }else if(previousWindow==2){
            getContentPane().remove(addDishesScreen);
        }else{
            try {
                getContentPane().remove(mainFrame);
                mainFrame.setClosed(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(AfterLoginScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    public AdminAfterLoginScreen() {
        initComponents();
        searchStudent.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainFrame = new javax.swing.JInternalFrame();
        searchStudent = new javax.swing.JButton();
        addDishesButton = new javax.swing.JButton();
        logoutAdminButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainFrame.setVisible(true);

        javax.swing.GroupLayout mainFrameLayout = new javax.swing.GroupLayout(mainFrame.getContentPane());
        mainFrame.getContentPane().setLayout(mainFrameLayout);
        mainFrameLayout.setHorizontalGroup(
            mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );
        mainFrameLayout.setVerticalGroup(
            mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(mainFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 0, 560, 530));

        searchStudent.setText("Search Student");
        searchStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchStudentActionPerformed(evt);
            }
        });
        getContentPane().add(searchStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 47, 190, 60));

        addDishesButton.setText("Add Dishes");
        addDishesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDishesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addDishesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 190, 60));

        logoutAdminButton.setText("Log out");
        logoutAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutAdminButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logoutAdminButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 190, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addDishesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDishesButtonActionPerformed
        // TODO add your handling code here:
          try {
            removeJpanelFrame();
            previousWindow=2;
            logger.log(Level.INFO, "previous window number  : {0} ",previousWindow);
        } catch (Exception ex) {
            Logger.getLogger(AfterLoginScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
         addDishesScreen = new AddDishesScreen();
         addDishesScreen.setVisible(true);
         getContentPane().add(addDishesScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 550, 530));
         pack();
    }//GEN-LAST:event_addDishesButtonActionPerformed

    private void logoutAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutAdminButtonActionPerformed
        // TODO add your handling code here:
        adminAfterLoginScreen.setVisible(false);
        SignUpPage.getSignUpPage().setVisible(true);
    }//GEN-LAST:event_logoutAdminButtonActionPerformed

    private void searchStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchStudentActionPerformed
            try {
            removeJpanelFrame();
            previousWindow=1;
            logger.log(Level.INFO, "previous window number  : {0} ",previousWindow);
        } catch (Exception ex) {
            Logger.getLogger(AfterLoginScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
         searchStudentScreen = new SearchStudentScreen();
         searchStudentScreen.setVisible(true);
         getContentPane().add(searchStudentScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 550, 530));
         pack();
    }//GEN-LAST:event_searchStudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAfterLoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAfterLoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAfterLoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAfterLoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAfterLoginScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDishesButton;
    private javax.swing.JButton logoutAdminButton;
    private javax.swing.JInternalFrame mainFrame;
    private javax.swing.JButton searchStudent;
    // End of variables declaration//GEN-END:variables
}
