/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.hostelmanagement.AfterLoginScreen.ProfileScreen;

import com.mycompany.hostelmanagement.DBConnection.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jahnavi
 */
public class Profilescreen extends javax.swing.JInternalFrame {
    private static final Logger logger = Logger.getLogger(Profilescreen.class.getName());
    public String loginIdImp ;
    
    public Connection connection =null;
    public Profilescreen(String loginId) {
        initComponents();
        loginIdImp=loginId;
        connection = DBConnection.getConnection();
            PreparedStatement readFromStudentsTable;
        try {
            readFromStudentsTable = connection.prepareStatement("select * from students where id=?");
            readFromStudentsTable.setString(1,loginIdImp);
            
            
            ResultSet profileIdResultSet = readFromStudentsTable.executeQuery();
            logger.log(Level.INFO, "Profile Name : read Successfuly from students table, profileId : {0}", loginIdImp);
            profileIdResultSet.next();
            String profileName = profileIdResultSet.getString(2);
            logger.log(Level.INFO, "Profile Name : read Successfuly from students table, name : {0}", profileName);
            dbname.setText(profileName);
            dbname.setEditable(false);
            
            String profileEmail = profileIdResultSet.getString(3);
            logger.log(Level.INFO, "Profile Email : read Successfuly from students table, email : {0}", profileEmail);
            dbemail.setText(profileEmail);
            dbemail.setEditable(false);
            
            String profileFatherName = profileIdResultSet.getString(4);
            logger.log(Level.INFO, "Profile FatherName : read Successfuly from students table, fathername : {0}", profileFatherName);
            dbfathername.setText(profileFatherName);
            dbfathername.setEditable(false);
            
            String profileMotherName = profileIdResultSet.getString(5);
            logger.log(Level.INFO, "Profile MotherName : read Successfuly from students table, mothername : {0}", profileMotherName);
            dbMotherName.setText(profileMotherName);
            dbMotherName.setEditable(false);
            
            String profileDateofBirth = profileIdResultSet.getString(6);
            logger.log(Level.INFO, "Profile DateofBirth : read Successfuly from students table, dob : {0}", profileDateofBirth);
            dbdob.setText(profileDateofBirth);
            dbdob.setEditable(false);
            
            String profileAddress = profileIdResultSet.getString(7);
            logger.log(Level.INFO, "Profile Address : read Successfuly from students table, address : {0}", profileAddress);
            dbAddress.setText(profileAddress);
            dbAddress.setEditable(false);
            
            String profileMobile = profileIdResultSet.getString(8);
            logger.log(Level.INFO, "Profile Mobile : read Successfuly from students table, mobile : {0}", profileMobile);
            dbMobile.setText(profileMobile);
            dbMobile.setEditable(false);
            
            String profileBranch = profileIdResultSet.getString(9);
            logger.log(Level.INFO, "Profile Branch : read Successfuly from students table, branch : {0}", profileBranch);
            dbBranch.setText(profileBranch);
            dbBranch.setEditable(false);
            
            String profileYear= profileIdResultSet.getString(10);
            logger.log(Level.INFO, "Profile Year : read Successfuly from students table, year : {0}", profileYear);
            dbYear.setText(profileYear);
            dbYear.setEditable(false);
            
            String profileGender= profileIdResultSet.getString(11);
            logger.log(Level.INFO, "Profile Gender : read Successfuly from students table, gender : {0}", profileGender);
            dbGender.setText(profileGender);
            dbGender.setEditable(false);
            
            

            
        } catch (SQLException ex) {
            Logger.getLogger(Profilescreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        namefield = new javax.swing.JTextField();
        dbYear = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        dbfathername = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        dbMotherName = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        dbdob = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        dbAddress = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        dbMobile = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        dbBranch = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        dbemail = new javax.swing.JTextField();
        dbname = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        dbGender = new javax.swing.JTextField();

        jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namefield.setEditable(false);
        namefield.setText("Name");
        jPanel.add(namefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 196, -1));

        dbYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbYearActionPerformed(evt);
            }
        });
        jPanel.add(dbYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 196, -1));

        jTextField14.setEditable(false);
        jTextField14.setText("Email");
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jPanel.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 190, -1));

        jTextField15.setEditable(false);
        jTextField15.setText("Father Name");
        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        jPanel.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 190, -1));

        dbfathername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbfathernameActionPerformed(evt);
            }
        });
        jPanel.add(dbfathername, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 196, -1));

        jTextField16.setEditable(false);
        jTextField16.setText("Mother Name");
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        jPanel.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 190, -1));

        dbMotherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbMotherNameActionPerformed(evt);
            }
        });
        jPanel.add(dbMotherName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 196, -1));

        jTextField17.setEditable(false);
        jTextField17.setText("Date of Birth");
        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });
        jPanel.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 190, -1));

        dbdob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbdobActionPerformed(evt);
            }
        });
        jPanel.add(dbdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 196, -1));

        jTextField19.setEditable(false);
        jTextField19.setText("Address");
        jTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField19ActionPerformed(evt);
            }
        });
        jPanel.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 190, -1));

        dbAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbAddressActionPerformed(evt);
            }
        });
        jPanel.add(dbAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 196, -1));

        jTextField20.setEditable(false);
        jTextField20.setText("Mobile");
        jTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField20ActionPerformed(evt);
            }
        });
        jPanel.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 190, -1));

        dbMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbMobileActionPerformed(evt);
            }
        });
        jPanel.add(dbMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 196, -1));

        jTextField21.setEditable(false);
        jTextField21.setText("Branch");
        jTextField21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField21ActionPerformed(evt);
            }
        });
        jPanel.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 190, -1));

        dbBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbBranchActionPerformed(evt);
            }
        });
        jPanel.add(dbBranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 196, -1));

        jTextField22.setEditable(false);
        jTextField22.setText("Year");
        jTextField22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField22ActionPerformed(evt);
            }
        });
        jPanel.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 190, -1));

        dbemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbemailActionPerformed(evt);
            }
        });
        jPanel.add(dbemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 196, -1));

        dbname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbnameActionPerformed(evt);
            }
        });
        jPanel.add(dbname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 196, -1));

        jTextField23.setEditable(false);
        jTextField23.setText("Gender");
        jTextField23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField23ActionPerformed(evt);
            }
        });
        jPanel.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 190, -1));

        dbGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbGenderActionPerformed(evt);
            }
        });
        jPanel.add(dbGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 196, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField23ActionPerformed

    private void jTextField22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField22ActionPerformed

    private void dbBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbBranchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dbBranchActionPerformed

    private void jTextField21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField21ActionPerformed

    private void dbMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dbMobileActionPerformed

    private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20ActionPerformed

    private void dbAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dbAddressActionPerformed

    private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19ActionPerformed

    private void dbdobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbdobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dbdobActionPerformed

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void dbMotherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbMotherNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dbMotherNameActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void dbfathernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbfathernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dbfathernameActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void dbemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dbemailActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void dbnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dbnameActionPerformed

    private void dbYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dbYearActionPerformed

    private void dbGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbGenderActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_dbGenderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dbAddress;
    private javax.swing.JTextField dbBranch;
    private javax.swing.JTextField dbGender;
    private javax.swing.JTextField dbMobile;
    private javax.swing.JTextField dbMotherName;
    private javax.swing.JTextField dbYear;
    private javax.swing.JTextField dbdob;
    private javax.swing.JTextField dbemail;
    private javax.swing.JTextField dbfathername;
    private javax.swing.JTextField dbname;
    private javax.swing.JPanel jPanel;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField namefield;
    // End of variables declaration//GEN-END:variables
}
